{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "from PIL import Image\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "# Path for face image database\n",
    "path = 'dataset/User'\n",
    "\n",
    "recognizer = cv2.face.LBPHFaceRecognizer_create()\n",
    "detector = cv2.CascadeClassifier(\"haarcascade_frontalface_default.xml\");\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting opencv-contrib-python\n",
      "  Using cached opencv_contrib_python-4.6.0.66-cp36-abi3-win_amd64.whl (42.5 MB)\n",
      "Collecting numpy>=1.14.5\n",
      "  Using cached numpy-1.24.1-cp39-cp39-win_amd64.whl (14.9 MB)\n",
      "Installing collected packages: numpy, opencv-contrib-python\n",
      "  Attempting uninstall: numpy\n",
      "    Found existing installation: numpy 1.24.1\n",
      "    Uninstalling numpy-1.24.1:\n",
      "      Successfully uninstalled numpy-1.24.1\n",
      "  Attempting uninstall: opencv-contrib-python\n",
      "    Found existing installation: opencv-contrib-python 4.6.0.66\n",
      "    Uninstalling opencv-contrib-python-4.6.0.66:\n",
      "      Successfully uninstalled opencv-contrib-python-4.6.0.66\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "    WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "  WARNING: The script f2py.exe is installed in 'C:\\Users\\Prasanna Reddy\\AppData\\Roaming\\Python\\Python39\\Scripts' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n",
      "    WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\\\Users\\\\Prasanna Reddy\\\\AppData\\\\Roaming\\\\Python\\\\Python39\\\\site-packages\\\\~-2\\\\cv2.pyd'\n",
      "Check the permissions.\n",
      "\n",
      "WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: You are using pip version 21.3.1; however, version 22.3.1 is available.\n",
      "You should consider upgrading via the 'C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\python.exe -m pip install --upgrade pip' command.\n"
     ]
    }
   ],
   "source": [
    "pip install --force-reinstall opencv-contrib-python --user"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting face_recognition\n",
      "  Using cached face_recognition-1.3.0-py2.py3-none-any.whl (15 kB)\n",
      "Collecting face-recognition-models>=0.3.0\n",
      "  Using cached face_recognition_models-0.3.0-py2.py3-none-any.whl\n",
      "Collecting numpy\n",
      "  Using cached numpy-1.24.1-cp39-cp39-win_amd64.whl (14.9 MB)\n",
      "Collecting dlib>=19.7\n",
      "  Using cached dlib-19.24.0.tar.gz (3.2 MB)\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Collecting Click>=6.0\n",
      "  Using cached click-8.1.3-py3-none-any.whl (96 kB)\n",
      "Collecting Pillow\n",
      "  Using cached Pillow-9.3.0-cp39-cp39-win_amd64.whl (2.5 MB)\n",
      "Collecting colorama\n",
      "  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)\n",
      "Building wheels for collected packages: dlib\n",
      "  Building wheel for dlib (setup.py): started\n",
      "  Building wheel for dlib (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for dlib\n",
      "Failed to build dlib\n",
      "Installing collected packages: colorama, Pillow, numpy, face-recognition-models, dlib, Click, face-recognition\n",
      "  Attempting uninstall: colorama\n",
      "    Found existing installation: colorama 0.4.6\n",
      "    Uninstalling colorama-0.4.6:\n",
      "      Successfully uninstalled colorama-0.4.6\n",
      "  Attempting uninstall: Pillow\n",
      "    Found existing installation: Pillow 9.3.0\n",
      "    Uninstalling Pillow-9.3.0:\n",
      "      Successfully uninstalled Pillow-9.3.0\n",
      "  Attempting uninstall: numpy\n",
      "    Found existing installation: numpy 1.24.1\n",
      "    Uninstalling numpy-1.24.1:\n",
      "      Successfully uninstalled numpy-1.24.1\n",
      "  Rolling back uninstall of numpy\n",
      "  Moving to c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\scripts\\f2py.exe\n",
      "   from C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-uninstall-jrv7cpsh\\f2py.exe\n",
      "  Moving to c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages\\numpy-1.24.1.dist-info\\\n",
      "   from C:\\Users\\Prasanna Reddy\\AppData\\Roaming\\Python\\Python39\\site-packages\\~umpy-1.24.1.dist-info\n",
      "  Moving to c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages\\numpy\\\n",
      "   from C:\\Users\\Prasanna Reddy\\AppData\\Roaming\\Python\\Python39\\site-packages\\~~mpy\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Prasanna Reddy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-1k31tjr_\\\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Prasanna Reddy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-1k31tjr_\\\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d 'C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-wheel-6kt68deh'\n",
      "       cwd: C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\\n",
      "  Complete output (95 lines):\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_py\n",
      "  running build_ext\n",
      "  C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\setup.py:129: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\n",
      "    if LooseVersion(cmake_version) < '3.1.0':\n",
      "  Building extension for Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]\n",
      "  Invoking CMake setup: 'cmake C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\tools\\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\build\\lib.win-amd64-cpython-39 -DPYTHON_EXECUTABLE=C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\build\\lib.win-amd64-cpython-39 -A x64'\n",
      "  -- Building for: Visual Studio 17 2022\n",
      "  -- The C compiler identification is MSVC 19.34.31935.0\n",
      "  -- The CXX compiler identification is MSVC 19.34.31935.0\n",
      "  -- Detecting C compiler ABI info\n",
      "  -- Detecting C compiler ABI info - failed\n",
      "  -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe\n",
      "  -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - broken\n",
      "  CMake Error at C:/Users/Prasanna Reddy/anaconda3/conda/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/CMakeTestCCompiler.cmake:70 (message):\n",
      "    The C compiler\n",
      "  \n",
      "      \"C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe\"\n",
      "  \n",
      "    is not able to compile a simple test program.\n",
      "  \n",
      "    It fails with the following output:\n",
      "  \n",
      "      Change Dir: C:/Users/Prasanna Reddy/AppData/Local/Temp/pip-install-1k31tjr_/dlib_7bce3822d3a04db38fbfb2467f5ca1c5/build/temp.win-amd64-cpython-39/Release/CMakeFiles/CMakeScratch/TryCompile-kw0fn1\n",
      "  \n",
      "      Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_9dca0.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:m && MSBuild version 17.4.0+18d5aef85 for .NET Framework\n",
      "        Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31935 for x64\n",
      "        Copyright (C) Microsoft Corporation.  All rights reserved.\n",
      "        testCCompiler.c\n",
      "        cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D \"CMAKE_INTDIR=\\\"Debug\\\"\" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo\"cmTC_9dca0.dir\\Debug\\\\\" /Fd\"cmTC_9dca0.dir\\Debug\\vc143.pdb\" /external:W3 /Gd /TC /errorReport:queue \"C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\build\\temp.win-amd64-cpython-39\\Release\\CMakeFiles\\CMakeScratch\\TryCompile-kw0fn1\\testCCompiler.c\"\n",
      "      C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppCommon.targets(703,5): error MSB6003: The specified task executable \"CL.exe\" could not be run. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\build\\temp.win-amd64-cpython-39\\Release\\CMakeFiles\\CMakeScratch\\TryCompile-kw0fn1\\cmTC_9dca0.dir\\Debug\\cmTC_9dca0.tlog'. [C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\build\\temp.win-amd64-cpython-39\\Release\\CMakeFiles\\CMakeScratch\\TryCompile-kw0fn1\\cmTC_9dca0.vcxproj]\n",
      "      C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppCommon.targets(703,5): error MSB6003:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\build\\temp.win-amd64-cpython-39\\Release\\CMakeFiles\\CMakeScratch\\TryCompile-kw0fn1\\cmTC_9dca0.vcxproj]\n",
      "      C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppCommon.targets(703,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\build\\temp.win-amd64-cpython-39\\Release\\CMakeFiles\\CMakeScratch\\TryCompile-kw0fn1\\cmTC_9dca0.vcxproj]\n",
      "      C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppCommon.targets(703,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\build\\temp.win-amd64-cpython-39\\Release\\CMakeFiles\\CMakeScratch\\TryCompile-kw0fn1\\cmTC_9dca0.vcxproj]\n",
      "      C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppCommon.targets(703,5): error MSB6003:    at System.IO.Directory.GetFiles(String path, String searchPattern) [C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\build\\temp.win-amd64-cpython-39\\Release\\CMakeFiles\\CMakeScratch\\TryCompile-kw0fn1\\cmTC_9dca0.vcxproj]\n",
      "      C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppCommon.targets(703,5): error MSB6003:    at Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\build\\temp.win-amd64-cpython-39\\Release\\CMakeFiles\\CMakeScratch\\TryCompile-kw0fn1\\cmTC_9dca0.vcxproj]\n",
      "      C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppCommon.targets(703,5): error MSB6003:    at Microsoft.Build.Utilities.CanonicalTrackedOutputFiles.InternalConstruct(ITask ownerTask, ITaskItem[] tlogFiles, Boolean constructOutputsFromTLogs) [C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\build\\temp.win-amd64-cpython-39\\Release\\CMakeFiles\\CMakeScratch\\TryCompile-kw0fn1\\cmTC_9dca0.vcxproj]\n",
      "      C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppCommon.targets(703,5): error MSB6003:    at Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode) [C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\build\\temp.win-amd64-cpython-39\\Release\\CMakeFiles\\CMakeScratch\\TryCompile-kw0fn1\\cmTC_9dca0.vcxproj]\n",
      "      C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppCommon.targets(703,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\build\\temp.win-amd64-cpython-39\\Release\\CMakeFiles\\CMakeScratch\\TryCompile-kw0fn1\\cmTC_9dca0.vcxproj]\n",
      "      C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppCommon.targets(703,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\build\\temp.win-amd64-cpython-39\\Release\\CMakeFiles\\CMakeScratch\\TryCompile-kw0fn1\\cmTC_9dca0.vcxproj]\n",
      "  \n",
      "  \n",
      "  \n",
      "  \n",
      "  \n",
      "    CMake will not be able to correctly generate this project.\n",
      "  Call Stack (most recent call first):\n",
      "    CMakeLists.txt:14 (project)\n",
      "  \n",
      "  \n",
      "  -- Configuring incomplete, errors occurred!\n",
      "  See also \"C:/Users/Prasanna Reddy/AppData/Local/Temp/pip-install-1k31tjr_/dlib_7bce3822d3a04db38fbfb2467f5ca1c5/build/temp.win-amd64-cpython-39/Release/CMakeFiles/CMakeOutput.log\".\n",
      "  See also \"C:/Users/Prasanna Reddy/AppData/Local/Temp/pip-install-1k31tjr_/dlib_7bce3822d3a04db38fbfb2467f5ca1c5/build/temp.win-amd64-cpython-39/Release/CMakeFiles/CMakeError.log\".\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\setup.py\", line 222, in <module>\n",
      "      setup(\n",
      "    File \"C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\lib\\site-packages\\setuptools\\__init__.py\", line 87, in setup\n",
      "      return distutils.core.setup(**attrs)\n",
      "    File \"C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 185, in setup\n",
      "      return run_commands(dist)\n",
      "    File \"C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 201, in run_commands\n",
      "      dist.run_commands()\n",
      "    File \"C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 973, in run_commands\n",
      "      self.run_command(cmd)\n",
      "    File \"C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\lib\\site-packages\\setuptools\\dist.py\", line 1217, in run_command\n",
      "      super().run_command(command)\n",
      "    File \"C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 992, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\lib\\site-packages\\wheel\\bdist_wheel.py\", line 325, in run\n",
      "      self.run_command(\"build\")\n",
      "    File \"C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 319, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\lib\\site-packages\\setuptools\\dist.py\", line 1217, in run_command\n",
      "      super().run_command(command)\n",
      "    File \"C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 992, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\lib\\site-packages\\setuptools\\command\\build.py\", line 24, in run\n",
      "      super().run()\n",
      "    File \"C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\lib\\site-packages\\setuptools\\_distutils\\command\\build.py\", line 132, in run\n",
      "      self.run_command(cmd_name)\n",
      "    File \"C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 319, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\lib\\site-packages\\setuptools\\dist.py\", line 1217, in run_command\n",
      "      super().run_command(command)\n",
      "    File \"C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 992, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\setup.py\", line 134, in run\n",
      "      self.build_extension(ext)\n",
      "    File \"C:\\Users\\Prasanna Reddy\\AppData\\Local\\Temp\\pip-install-1k31tjr_\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\setup.py\", line 171, in build_extension\n",
      "      subprocess.check_call(cmake_setup, cwd=build_folder)\n",
      "    File \"C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\lib\\subprocess.py\", line 373, in check_call\n",
      "      raise CalledProcessError(retcode, cmd)\n",
      "  subprocess.CalledProcessError: Command '['cmake', 'C:\\\\Users\\\\Prasanna Reddy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-1k31tjr_\\\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\\\tools\\\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\\\Users\\\\Prasanna Reddy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-1k31tjr_\\\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\\\build\\\\lib.win-amd64-cpython-39', '-DPYTHON_EXECUTABLE=C:\\\\Users\\\\Prasanna Reddy\\\\anaconda3\\\\conda\\\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\\\Users\\\\Prasanna Reddy\\\\AppData\\\\Local\\\\Temp\\\\pip-install-1k31tjr_\\\\dlib_7bce3822d3a04db38fbfb2467f5ca1c5\\\\build\\\\lib.win-amd64-cpython-39', '-A', 'x64']' returned non-zero exit status 1.\n",
      "  ----------------------------------------\n",
      "  ERROR: Failed building wheel for dlib\n",
      "WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "    WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "    WARNING: Ignoring invalid distribution - (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "    WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "    WARNING: Ignoring invalid distribution - (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "    WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "    WARNING: Ignoring invalid distribution - (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\\\Users\\\\Prasanna Reddy\\\\anaconda3\\\\conda\\\\Lib\\\\site-packages\\\\numpy\\\\core\\\\_multiarray_tests.cp39-win_amd64.pyd'\n",
      "Consider using the `--user` option or check the permissions.\n",
      "\n",
      "WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -pencv-contrib-python (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\users\\prasanna reddy\\appdata\\roaming\\python\\python39\\site-packages)\n",
      "WARNING: You are using pip version 21.3.1; however, version 22.3.1 is available.\n",
      "You should consider upgrading via the 'C:\\Users\\Prasanna Reddy\\anaconda3\\conda\\python.exe -m pip install --upgrade pip' command.\n"
     ]
    }
   ],
   "source": [
    "pip install --force-reinstall face_recognition"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      " [INFO] Training faces. It will take a few seconds. Wait ...\n",
      "\n",
      " [INFO] 1 faces trained. Exiting Program\n"
     ]
    }
   ],
   "source": [
    "# function to get the images and label data\n",
    "def getImagesAndLabels(path):\n",
    "\n",
    "    imagePaths = [os.path.join(path,f) for f in os.listdir(path)]     \n",
    "    faceSamples=[]\n",
    "    ids = []\n",
    "\n",
    "    for imagePath in imagePaths:\n",
    "\n",
    "        PIL_img = Image.open(imagePath).convert('L') # convert it to grayscale\n",
    "        img_numpy = np.array(PIL_img,'uint8')\n",
    "\n",
    "        id = int(os.path.split(imagePath)[-1].split(\".\")[1])\n",
    "        faces = detector.detectMultiScale(img_numpy)\n",
    "\n",
    "        for (x,y,w,h) in faces:\n",
    "            faceSamples.append(img_numpy[y:y+h,x:x+w])\n",
    "            ids.append(id)\n",
    "\n",
    "    return faceSamples,ids\n",
    "\n",
    "print (\"\\n [INFO] Training faces. It will take a few seconds. Wait ...\")\n",
    "faces,ids = getImagesAndLabels(path)\n",
    "recognizer.train(faces, np.array(ids))\n",
    "\n",
    "# Save the model into trainer/trainer.yml\n",
    "recognizer.write('trainer/trainer.yml') # recognizer.save() worked on Mac, but not on Pi\n",
    "\n",
    "# Print the numer of faces trained and end program\n",
    "print(\"\\n [INFO] {0} faces trained. Exiting Program\".format(len(np.unique(ids))))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "anaconda-cloud": {},
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  },
  "vscode": {
   "interpreter": {
    "hash": "e6afa45da3ca9d4da371ea728ab237140b2a1c07c96fbb2b8226b51568f8db68"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
